version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: '11:00'
    timezone: Asia/Kolkata
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - ">= 1.3.3-native-mt.a, < 1.3.4"
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - "> 1.3.5, < 1.4"
