name: CI
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java_version: [1.8, 10, 11, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - run: |
          ./gradlew spotlessCheck
          ./gradlew test
          ./gradlew build

      - uses: actions/upload-artifact@master
        with:
          name: ExtensionTests_results.xml
          path: build/test-results/test/TEST-me.msfjarvis.wallsbot.ExtensionTests.xml
